name: Install 1Password CLI
description: Install 1Password CLI in your pipeline
author: 1Password
branding:
  icon: lock
  color: blue
inputs:
  version:
    description: Mention the specific version of the 1Password CLI to be installed
    default: "latest"
runs:
  using: composite
  steps:
    - shell: bash
      env:
        OP_CLI_VERSION: ${{ inputs.version }}
      run: |
        ${{ github.action_path }}/install-cli.sh
