name: 1Password CLI
description: Install 1Password CLI in your pipeline
author: 1Password
branding:
  icon: lock
  color: blue
inputs:
  version:
    description: Specify which 1Password CLI version to install. Defaults to "latest".
    default: "latest"
runs:
  using: composite
  steps:
    - shell: bash
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      env:
        OP_CLI_VERSION: ${{ inputs.version }}
      run: |
        ${{ github.action_path }}/install-cli.sh
    - shell: pwsh
      if: ${{ runner.os == 'Windows' }}
      env:
        OP_CLI_VERSION: ${{ inputs.version }}
      run: |
        ${{ github.action_path }}\install-cli.ps1
