// AUTO-GENERATED by scripts/update-fallback-versions.mjs — do not edit by hand.
// Last-resort CLI versions, used only when both app-updates and Docker Hub are
// unavailable. Refresh with `npm run op-version` (see release docs).
import type { ReleaseChannel } from "./constants";

export const FALLBACK_VERSIONS: Record<ReleaseChannel, string> = {
	latest: "2.35.0",
	"latest-beta": "2.37.0-beta.01",
};
