on: push
name: Test installation

jobs:
  use-latest-version:
    name: "Test getting latest stable CLI version"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install 1Password CLI
        uses: ./ # 1password/install-cli-action@<version>
      - name: Check CLI version
        run: ./test/assert-version.sh latest
  use-latest-beta-version:
    name: "Test getting latest CLI beta version"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install 1Password CLI
        uses: ./ # 1password/install-cli-action@<version>
        with:
          version: latest-beta
      - name: Check CLI version
        run: ./test/assert-version.sh latest-beta
  use-specific-version:
    name: "Test getting a specific CLI version"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install 1Password CLI
        uses: ./ # 1password/install-cli-action@<version>
        with:
          version: 2.16.0
      - name: Check CLI version
        run: ./test/assert-version.sh 2.16.0
